# Generated by Django 5.0.6 on 2024-07-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0003_rename_collateral_number_sales_collateral_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='actual_amount_sold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='profit_or_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
