# Generated by Django 5.0.6 on 2024-07-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0004_sales_actual_amount_sold_sales_profit_or_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='reference_number',
        ),
    ]
