# Generated by Django 5.0.6 on 2024-08-02 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0005_remove_expenses_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
