# Generated by Django 5.0.6 on 2024-08-02 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0006_payments_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeloans',
            name='date_of_loan',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='date_of_sale',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_of_expense',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
