# Generated by Django 5.0.6 on 2024-08-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0007_activeloans_date_of_loan_sales_date_of_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackers',
            name='reference_number',
        ),
    ]
