# Generated by Django 5.0.6 on 2024-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0008_remove_trackers_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackers',
            name='client_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
